version: '3'
services:
    dynamodb:
        image: amazon/dynamodb-local
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup
        volumes:
            - dynamodb:/home/dynamodblocal
        ports:
            - 8000:8000
    awscli:
        build:
            context: .
            dockerfile: Dockerfile-awscli
        entrypoint: [""]
        tty: true
        command:
            - /bin/sh
        volumes:
            - ./bin:/usr/app
volumes:
    dynamodb:
        driver: local
    bin:
        driver: local      